# Generated by Django 4.2.7 on 2026-05-31 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='budget',
            name='categories__user_id_2c796f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='level',
            field=models.CharField(choices=[('warning', 'Warning'), ('exceeded', 'Exceeded')], default='warning', max_length=10),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='budgetalert',
            name='percentage_used',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'period')},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'period'], name='categories__user_id_8e73ca_idx'),
        ),
    ]
