# Generated by Django 4.2.7 on 2026-05-31 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SplitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percentage', 'Percentage'), ('shares', 'Shares')], default='equal', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SplitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_split_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='splits.splitgroup')),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_memberships', to='splits.guestuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_settled', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='splits.splitexpense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='splits.splitgroupmember')),
            ],
        ),
        migrations.AddField(
            model_name='splitexpense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='splits.splitgroup'),
        ),
        migrations.AddField(
            model_name='splitexpense',
            name='paid_by_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_split_expenses', to='splits.guestuser'),
        ),
        migrations.AddField(
            model_name='splitexpense',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_split_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SplitSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='splits.splitgroup')),
                ('payer_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to='splits.splitgroupmember')),
                ('receiver_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to='splits.splitgroupmember')),
            ],
            options={
                'indexes': [models.Index(fields=['group'], name='splits_spli_group_i_373e7c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='splitgroupmember',
            index=models.Index(fields=['group'], name='splits_spli_group_i_f7944c_idx'),
        ),
        migrations.AddIndex(
            model_name='splitgroup',
            index=models.Index(fields=['created_by'], name='splits_spli_created_2c9524_idx'),
        ),
        migrations.AddIndex(
            model_name='splitexpenseshare',
            index=models.Index(fields=['expense', 'member'], name='splits_spli_expense_ab4dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='splitexpense',
            index=models.Index(fields=['group', 'date'], name='splits_spli_group_i_b45ba3_idx'),
        ),
    ]
